name: Build and Push Docker image to Google Artifact Registry

on:
  push:
    branches:
      - main # Set a branch name to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Artifact Registry
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: YOUR_PROJECT_ID
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker YOUR_ARTIFACT_REGISTRY_REGION-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: YOUR_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_ARTIFACT_REGISTRY_REPOSITORY_NAME/YOUR_IMAGE_NAME:YOUR_TAG
